import { Inter } from 'next/font/google'
import './globals.css'
import {FontAwesomeIcon} from '@fortawesome/react-fontawesome'
import '@fortawesome/fontawesome-free'
import {library} from '@fortawesome/fontawesome-svg-core'
import {far} from '@fortawesome/free-regular-svg-icons'
import {fas} from '@fortawesome/free-solid-svg-icons'
import {fab} from '@fortawesome/free-brands-svg-icons'
library.add(far,fas,fab);

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Mathan Portfolio',
  description: 'Generated by Mathan Jayapal ',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
                        <script src="https://kit.fontawesome.com/e20sdfsd9.js" crossOrigin="anonymous"></script>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
